CREATE VIEW reconcile_view AS 
SELECT 
t2.custid, 
t2.username, 
t2.quote_count, 
t2.ip, 
t2.entry_time, 
t2.prp_1, 
t2.prp_2, 
t2.prp_3, 
t2.ms, 
t2.http_type, 
t2.purchase_category, 
t2.total_count, 
t2.purchase_sub_category, 
t2.http_info, 
t2.status_code, 
t2.year, 
t2.month FROM (SELECT *,ROW_NUMBER() OVER (PARTITION BY custid ORDER BY -1) rn FROM (SELECT * FROM one  UNION ALL SELECT *FROM tbl_orc_two) t1) t2 WHERE rn = 1;

